### ISSUE TITLE
[meta] Roadmap v3

### ISSUE THREAD

**Issue by NekR** [NekR/offline-plugin#36]
## Overview

`v3` is going to fix most import issues in this plugin and here is what was done so far: [CHANGELOG](https://github.com/NekR/offline-plugin/blob/v3/CHANGELOG.md)

## What is planned

* [x] Update and reformat README to match latest changes (_in progress_)
* [x] Store assets-hashed in ServiceWorker and always use `updateStrategy: 'changed'` to download only changed assets, even with different name (existed assets are renamed if needed). [Issue #6](https://github.com/NekR/offline-plugin/issues/6)
* ~~Runtime URLs/externals matching. Right now one can use `sw-toolbox` to do this (include it in SW's `entry`), but I want this to be fully declarative to be able to generate code for other targets, e.g. Java/Swift code for Cordova. [Issue 26](https://github.com/NekR/offline-plugin/issues/26)~~ (not for a `v3` anymore)
* [x] [Concider make additional cache not fail on individual errors](https://github.com/NekR/offline-plugin/issues/28)
* [x] Test SW generation with source-maps [Issue 42](https://github.com/NekR/offline-plugin/issues/42)
* ~~Check fetched file's hash before caching [Issue 43](https://github.com/NekR/offline-plugin/issues/43)~~ Invalid.
* [x] Add basic lifetime events for AppCache [Issue 44](https://github.com/NekR/offline-plugin/issues/44)

___________________________________

This is most important things planned for `v3`. Other things may be added later, but is the roadmap at a moment.

**Comment by NekR** [comment]
cc @amiuhle

**Comment by amiuhle** [comment]
What's your opinion on switching to a Promise based API for the runtime?

**Comment by NekR** [comment]
It requires at least Promise polyfill because plugin supports AppCache too. What is the point of having it?

**Comment by NekR** [comment]
Almost ready to `v3` :-)

**Comment by amiuhle** [comment]
Nice! I might be able to contribute some more towards the end of the week, right now I have other stuff to do, unfortunately...

**Comment by NekR** [comment]
Yay! `v3` is released and now in master. README is updated accordingly, but docs still on its way. Thanks for your help 👍
